import Head from "next/head";
import styles from "@/styles/Home.module.css";
import axios from "axios";

export default function Home() {
  const saveUser = () => {
    axios.post("/api/mint", {
      // user: "@nico",
      // user: "@jota",
      user: "@hugo",
      location: { lat: 19.3, log: 45.6 },
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={saveUser}>Save</button>
      </main>
    </>
  );
}
